#ifndef CERT_H
#define CERT_H

#include <stdint.h>

/**
 * @brief Pointer to the start and end of the CA certificate in binary form.
 * These symbols are generated by the linker when you add the certificate file
 * (e.g. ca_crt.pem) to your project and reference it in CMakeLists.txt or component.mk.
 */
extern const uint8_t ca_root_cert_start[] asm("_binary_ca_crt_start");
extern const uint8_t ca_root_cert_end[]   asm("_binary_ca_crt_end");

/**
 * @brief Pointer to the start and end of the client certificate in binary form
 */
extern const uint8_t client_cert_start[] asm("_binary_client_crt_start");
extern const uint8_t client_cert_end[]   asm("_binary_client_crt_end");

/**
 * @brief Pointer to the start and end of the client private key in binary form
 */
extern const uint8_t client_key_start[] asm("_binary_client_key_start");
extern const uint8_t client_key_end[]   asm("_binary_client_key_end");

#endif // CERT_H